### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by sdwulxr** [zhangzheng1997/SSEGCN-ABSA#10]
Traceback (most recent call last):
  File "F:\Code\SSEGCN-ABSA-main\train.py", line 373, in <module>
    main()
  File "F:\Code\SSEGCN-ABSA-main\train.py", line 370, in main
    ins.run()
  File "F:\Code\SSEGCN-ABSA-main\train.py", line 243, in run
    max_test_acc, max_f1, model_path = self._train(criterion, optimizer, max_test_acc_overall)
  File "F:\Code\SSEGCN-ABSA-main\train.py", line 169, in _train
    outputs, penal = self.model(inputs)
  File "F:\Anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Code\SSEGCN-ABSA-main\models\ssegcn_bert.py", line 37, in forward
    outputs1 = self.gcn_model(inputs)
  File "F:\Anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Code\SSEGCN-ABSA-main\models\ssegcn_bert.py", line 51, in forward
    h = self.gcn(inputs)    
  File "F:\Anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Code\SSEGCN-ABSA-main\models\ssegcn_bert.py", line 96, in forward
    sequence_output = self.layernorm(sequence_output)
  File "F:\Anaconda\envs\DL\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Code\SSEGCN-ABSA-main\models\ssegcn_bert.py", line 24, in forward
    mean = x.mean(-1, keepdim=True)
AttributeError: 'str' object has no attribute 'mean'
在运行ssegcn_bert的时候报这个错误是为什么呀，各位大佬帮忙看一下，你们有没有出现这个错误呀？谢谢

**Comment by mesmaeili96** [comment]
Exactly i have this problem too!

**Comment by think-home** [comment]
so How to solve it?

**Comment by ccflyu** [comment]
请问解决了吗

**Comment by sunjinzhao998** [comment]
> 请问解决了吗

将原先的代码
  sequence_output, pooled_output = self.bert(text_bert_indices, attention_mask=attention_mask, token_type_ids=bert_segments_ids)
换为        
        outputs = self.bert(text_bert_indices, attention_mask=attention_mask, token_type_ids=bert_segments_ids) 
        sequence_output, pooled_output = outputs.last_hidden_state, outputs.pooler_output

**Comment by ccflyu** [comment]
> > 请登录
> 
> 将原先的代码 sequence_output, pooled_output = self.bert (text_bert_indices,tention_mask=attention_mask, token_type_ids=bert_segments_ids) 换为outputs = self.bert(text_bert_indices,tention_mask=attention_mask, token_type_ids=bert_segments_ids) sequence_output,pooled_output =outputs.last_hidden_​​state,outputs.pooler_output

非常感谢您的回复
